= Pipeline-Util

Utility to show status of https://gitlab.com/explore/projects[Gitlab] CI/CD pipelines as a command line utility.

.Examplary output of the command (uncolored).
[source]
----
python PipelineUtil.py --projects my-app --references release --verbose
my-group / my-app
|- 2047173 --------- release -----------------------> success
|- 2047172 --------- release -----------------------> failed
   # https://gitlab.com/my-group/my-app/-/pipelines/2047172
   > test                junit                            failed
----

== Requirements

Mainly based on https://python-gitlab.readthedocs.io/en/stable/gl_objects/projects.html[gitlab-python].

. python installation
. installed dependencies
* `python -m pip install python-gitlab`
* `python -m pip install truststore`

== Usage

. run `python PipelineUtil.py --help` for usage information.

== Customization

Using a self-managed gitlab instance and private repositories can be accessed by providing the url and token as parameters or as environment variables (_PIPELINEUTIL_URL_, _PIPELINEUTIL_TOKEN_).

Self-managed gitlab instances secured with self-signed certificates might require you provide the certificate authority's certificate. `truststore` is used to access the native system certificate stores. Otherwise, import the certicate authority's certificate into the certifi certificate store (located at `python -c "import certifi;print(certifi.where());"`).
