= Pipeline-Util

Utility to show status of https://gitlab.com/explore/projects[Gitlab] CI/CD pipelines as a command line utility.

.Examplary output of the command (uncolored).
[source]
----
./PipelineUtil.py run --projects my-app --references release --verbose
my-group / my-app
|- 2047173 --------- release -----------------------> success
|- 2047172 --------- release -----------------------> failed
   # https://gitlab.com/my-group/my-app/-/pipelines/2047172
   > test                junit                            failed
----

== Requirements

Mainly based on https://python-gitlab.readthedocs.io/en/stable/gl_objects/projects.html[gitlab-python].

. python installation
. installed dependencies (i.e. `pip install .`)

== Usage

* run `./PipelineUtil.py --help` for usage information.

== Customization

Access to multiple gitlab instances can be configured via the CLI. +
Alternatively, use environment variables (_PIPELINEUTIL_URL_, _PIPELINEUTIL_TOKEN_) for a minimal setup.

Gitlab instances may be secured with self-signed certificates.
`truststore` is used to access the native system's certificate stores.
Alternatively, append the certicate authority's certificate to the certifi certificate store.
It's location can be displayed by running:

[source,shell]
----
python -c "import certifi;print(certifi.where())"
----
